export enum RebrickableActionNames {
  LOAD_THEMES_INIT = 'LOAD_THEMES_INIT',
  LOAD_THEMES_ERROR = 'LOAD_THEMES_ERROR',
  LOAD_THEMES_SUCCESS = 'LOAD_THEMES_SUCCESS',
  LOAD_SETS_INIT = 'LOAD_SETS_INIT',
  LOAD_SETS_ERROR = 'LOAD_SETS_ERROR',
  LOAD_SETS_SUCCESS = 'LOAD_SETS_SUCCESS'
}
