//import '@storybook/addon-knobs/register'
//import 'storybook-addon-jsx/register'
//import '@storybook/addon-notes/register'
import './sourceRegister'
import './selectFirstStoryAddon'
//import '@storybook/addon-links/register'
