//import '@storybook/addon-knobs/register'
//import 'storybook-addon-jsx/register'
//import '@storybook/addon-notes/register'
import './sourceCodeUtils/sourceRegister'
import './presentationPanel/presentationRegister'
import './selectFirstStoryAddon'
//import '@storybook/addon-links/register'
