export enum RebrickableActionNames {
  LOAD_THEMES_INIT = 'REBRICKABLE::LOAD_THEMES_INIT',
  LOAD_THEMES_ERROR = 'REBRICKABLE::LOAD_THEMES_ERROR',
  LOAD_THEMES_SUCCESS = 'REBRICKABLE::LOAD_THEMES_SUCCESS',
  LOAD_SETS_INIT = 'REBRICKABLE::LOAD_SETS_INIT',
  LOAD_SETS_ERROR = 'REBRICKABLE::LOAD_SETS_ERROR',
  LOAD_SETS_SUCCESS = 'REBRICKABLE::LOAD_SETS_SUCCESS'
}
